ALL_VALID: yes

DESCRIPTION_KEYWORDS_I:
  - "windows"
  - "nessus"
  - "azure "
  - "entraid"
  - "aws"
  - "adobe"
  - "servicenow"
  - "mac"
  - "keeper"
  - "wazuh"
  - "thehive"
  - "splunk"
  - "microsoft"
  - "phishing"
  - "okta"
DESCRIPTION_KEYWORDS:

PRODUCT_KEYWORDS_I:

PRODUCT_KEYWORDS:
