ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
  - "nessus"
  - "azure"
  - "entraid"
  - "aws "
  - "keeper"
  - "wazuh"
  - "thehive "
  - "splunk "
  - "microsoft "
  - "okta "
  - "Palo Alto "

DESCRIPTION_KEYWORDS:
PRODUCT_KEYWORDS_I:
PRODUCT_KEYWORDS:
