name: botpeas_action

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9' 

      - name: Setup Dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run CVEs Monitor
        run: python3 botpeas.py
        shell: bash
        env:
          TEAMS_WEBHOOK_DEV: ${{ secrets.TEAMS_WEBHOOK_DEV }}
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}

      - name: Create local changes
        run: git add output/botpeas.json

      - name: Commit results to Github
        run: |
            git config --local user.email ""
            git config --global user.name "BotPEASS"
            git commit -m "Bot auto update" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}

